## Feature Preparation

In [55]:
import pandas as pd

In [56]:
df=pd.read_csv('online food delivery.csv')

In [57]:
df

,Unnamed: 0,age,gender,marital_status,occupation,monthly_income,educational_qualifications,family_size,customer_type,latitude,longitude,pin_code,output,feedback,unnamed:_13
0,0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive,Yes
1,1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive,Yes
2,2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative,Yes
3,3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive,Yes
4,4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,355,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive,No
281,363,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive,Yes
282,369,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive,Yes
283,374,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative,Yes
284,386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive,Yes

In [58]:
df['output'].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [59]:
df.drop(columns= ['Unnamed: 0','unnamed:_13'],inplace=True)
df

,age,gender,marital_status,occupation,monthly_income,educational_qualifications,family_size,customer_type,latitude,longitude,pin_code,output,feedback
0,20,Female,Single,Student,No Income,Post Graduate,4,Frequent,12.9766,77.5993,560001,Yes,Positive
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,Regular,12.9770,77.5773,560009,Yes,Positive
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,Regular,12.9551,77.6593,560017,Yes,Negative
3,22,Female,Single,Student,No Income,Graduate,6,Frequent,12.9473,77.5616,560019,Yes,Positive
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,Frequent,12.9850,77.5533,560010,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,21,Male,Single,Student,No Income,Graduate,2,Regular,13.0012,77.5995,560046,No,Positive
281,31,Male,Married,Employee,More than 50000,Ph.D,3,Regular,12.9306,77.5434,560085,Yes,Positive
282,30,Male,Married,Employee,More than 50000,Post Graduate,6,Frequent,12.9369,77.6407,560095,Yes,Positive
283,21,Male,Single,Student,No Income,Graduate,3,Regular,13.0641,77.5931,560092,Yes,Negative
284,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,Regular,12.9770,77.5773,560009,Yes,Positive

In [ ]:
numerical_data=df[['age','family_size','latitude','longitude','pin_code']]
nominal=df[['gender','marital_status','occupation','monthly_income','educational_qualifications','customer_type']]
y=df['output']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
nominal_data=ohe.fit_transform(nominal)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
output=le.fit_transform(y)

In [90]:
nominal_df = pd.DataFrame(
    nominal_data,
    columns=ohe.get_feature_names_out(nominal.columns),
    index=df.index
)

In [91]:
features = pd.concat([numerical_data, nominal_df], axis=1)
target = output

In [92]:
features

,age,family_size,latitude,longitude,pin_code,gender_Female,gender_Male,marital_status_Married,marital_status_Prefer not to say,marital_status_Single,...,monthly_income_More than 50000,monthly_income_No Income,educational_qualifications_Graduate,educational_qualifications_Ph.D,educational_qualifications_Post Graduate,educational_qualifications_School,educational_qualifications_Uneducated,customer_type_Frequent,customer_type_New,customer_type_Regular
0,20,4,12.9766,77.5993,560001,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,24,3,12.9770,77.5773,560009,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,22,3,12.9551,77.6593,560017,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,22,6,12.9473,77.5616,560019,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,22,4,12.9850,77.5533,560010,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,21,2,13.0012,77.5995,560046,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
281,31,3,12.9306,77.5434,560085,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
282,30,6,12.9369,77.6407,560095,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
283,21,3,13.0641,77.5931,560092,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
284,23,2,12.9770,77.5773,560009,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [93]:
target

     0
0    1
1    1
2    1
3    1
4    1
..  ..
280  0
281  1
282  1
283  1
284  1

[285 rows x 1 columns]